### ISSUE TITLE
使用同时剪层和通道

### ISSUE THREAD

**Issue by qybing** [tanluren/yolov3-channel-and-layer-pruning#102]
python layer_channel_prune.py --cfg cfg/my_cfg.cfg --data data/my_data.data --weights weights/last.pt --shortcuts 12 --global_percent 0.8 --layer_keep 0.1 
Traceback (most recent call last):
  File "layer_channel_prune.py", line 272, in <module>
    compact_model2 = Darknet([compact_model1.hyperparams.copy()] + compact_module_defs, (img_size, img_size)).to(device)
  File "/opt/code/YOLO/yolov3-channel-and-layer-pruning/models.py", line 223, in __init__
    self.module_list, self.routs, self.hyperparams = create_modules(self.module_defs, img_size, arc)
  File "/opt/code/YOLO/yolov3-channel-and-layer-pruning/models.py", line 57, in create_modules
    filters = sum([output_filters[i + 1 if i > 0 else i] for i in layers])
  File "/opt/code/YOLO/yolov3-channel-and-layer-pruning/models.py", line 57, in <listcomp>
    filters = sum([output_filters[i + 1 if i > 0 else i] for i in layers])
IndexError: list index out of range

**Comment by tanluren** [comment]
已更新这个脚本
