### ISSUE TITLE
AssertionError: No labels found. Recommend correcting image and label paths.

### ISSUE THREAD

**Issue by GraceKafuu** [tanluren/yolov3-channel-and-layer-pruning#13]
loaded weights from weights/yolov3.weights
Reading labels: 100%|████████████████████████| 20/20 [00:00<00:00, 78251.94it/s]
Traceback (most recent call last):
  File "train.py", line 497, in <module>
    train()  # train normally
  File "train.py", line 239, in train
    cache_images=False if opt.prebias else opt.cache_images)
  File "/home/nvidia/yolov3-channel-and-layer-pruning-master/utils/datasets.py", line 373, in __init__
    assert nf > 0, 'No labels found. Recommend correcting image and label paths.'
AssertionError: No labels found. Recommend correcting image and label paths.

这个路径该怎么设置，我的数据没有问题，之前用darknet跑过，现在是放在本项目的路径下报这个错，放在darknet那边也是这样。
大神，下一步怎么处理？

**Comment by GraceKafuu** [comment]
没事了，仔细看了converter.py,现在跑起来了 >_<

**Comment by tanluren** [comment]
嗯嗯数据格式标准可以看这里https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data，images和labels路径注意要刚好能替换

**Comment by 95cdy** [comment]
> 没事了，仔细看了converter.py,现在跑起来了 >_<

请问怎么解决的这个问题
