### ISSUE TITLE
list out of range

### ISSUE THREAD

**Issue by yulinhuyang** [tanluren/yolov3-channel-and-layer-pruning#75]
![image](https://user-images.githubusercontent.com/13074332/82969210-b167c200-a001-11ea-84ec-aa9164c8e2af.png)

**Comment by yulinhuyang** [comment]
Traceback (most recent call last):
  File "layer_channel_prune.py", line 273, in <module>
    compact_model2 = Darknet([compact_model1.hyperparams.copy()] + compact_module_defs, (img_size, img_size)).to(device)
  File "/data1/visiondection/detection/yolov3-channel-and-layer-pruning-master/yolov3-channel-and-layer-pruning-master/models.py", line 221, in __init__
    self.module_list, self.routs, self.hyperparams = create_modules(self.module_defs, img_size, arc)
  File "/data1/visiondection/detection/yolov3-channel-and-layer-pruning-master/yolov3-channel-and-layer-pruning-master/models.py", line 57, in create_modules
    filters = sum([output_filters[i + 1 if i > 0 else i] for i in layers])
  File "/data1/visiondection/detection/yolov3-channel-and-layer-pruning-master/yolov3-channel-and-layer-pruning-master/models.py", line 57, in <listcomp>
    filters = sum([output_filters[i + 1 if i > 0 else i] for i in layers])
IndexError: list index out of range
