### ISSUE TITLE
运行代码问题，只要训练二分类，就报错

### ISSUE THREAD

**Issue by xupengao** [tanluren/yolov3-channel-and-layer-pruning#77]
Traceback (most recent call last):
  File "train.py", line 542, in <module>
    train()  # train normally
  File "train.py", line 418, in train
    save_json=final_epoch and epoch > 0 and 'coco.data' in data)
  File "/home/sdu/yolov3-channel-and-layer-pruning/test.py", line 194, in test
    maps[c] = ap[i]
IndexError: index 2 is out of bounds for axis 0 with size 2
，其他分类训练没有问题，只要classes是2，就报上面的错误，是怎么回事

**Comment by tanluren** [comment]
检查下.data中的classes有没有改对

**Comment by xupengao** [comment]
检查过了，改成其他的分类就不会出错，请问测试过二分类模型么

**Comment by larsonwu0220** [comment]
剛做完二分類訓練，沒有問題阿，檢查看看你的 label 有沒有 2 以上的，確認 label 只有0和1。
