### ISSUE TITLE
yolov4-tiny.cfg RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 875238

### ISSUE THREAD

**Issue by RnYngxx** [tanluren/yolov3-channel-and-layer-pruning#97]
The following error occurred when I use yolov4-tiny.cfg:
Traceback (most recent call last):
  File "/Users/ren_yx/PycharmProjects/Object detection/YOLO_pruning/train.py", line 542, in <module>
    train()  # train normally
  File "/Users/ren_yx/PycharmProjects/Object detection/YOLO_pruning/train.py", line 143, in train
    cutoff = load_darknet_weights(model, weights)
  File "/Users/ren_yx/PycharmProjects/Object detection/YOLO_pruning/models.py", line 353, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr:ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 875238

**Comment by tanluren** [comment]
上传的cfg不对，已更新
